name: docker

on: [push, pull_request]

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: Sansui233
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: Sansui233/proxypool/proxypool
          tag_with_ref: true
